variables:
  #Build
  buildCommand: 'python setup.py bdist_wheel'
  #AzureSubscription
  azureSubscription: 'sc_datamngtdev_poc'
  #Resource Group
  resource_group: 'target_architecture_poc'
  region: 'westeurope'
  #Artifacts
  azureArtifacts: 'sc_up_artifacts_py_common_pipelines'
  artifactsFeed: 'igtpoc/common'
  #Databricks Workspace
  databricks_workspace: 'dbw-da-demo'
  databricks_cluster_name: 'dbw-autocl-da-demo-01'
  #Storage Account to Upload
  destination: 'AzureBlob'
  storage: 'dlsdadev01'
  containerName: 'artifacts'