parameters:
  - name: environmentName
    displayName: Variable group name for environment to deploy
    type: string
  - name: usePairInfrastructure
    displayName: Use Pair Infrastructure
    default: false
    type: boolean

variables:
  - group: ${{ parameters.environmentName }}
  - name: terraformVersion
    value: "1.5.0"
  - name: terraformResourceGroupName
    value: rg-$(terraform_in_environment_type)-$(terraform_in_project)-$(terraform_in_location_short)-state
  - name: terraformSaName
    value: sa$(terraform_in_environment_type)$(terraform_in_project)$(terraform_in_location_short)tfstate
  - name: terraformBackendContainerName
    value: $(terraform_in_environment_type)tfstate
  - ${{ if eq(parameters.usePairInfrastructure, false) }}:
    - name: azureDevOpsPool
      value: ${{ parameters.environmentName }}-agentpool
  - ${{ if eq(parameters.usePairInfrastructure, true) }}:
    - name: azureDevOpsPool
      value: ${{ parameters.environmentName }}-pair-agentpool

trigger: none

stages:
  - stage: create_browser_authentication_endpoint
    displayName: Create Databricks browser authentication endpoint
    jobs:
      - job: create_browser_authentication_endpoint
        displayName: Create browser authentication endpoint
        pool:
          name: ${{ variables.azureDevOpsPool }}
        steps:
          - template: azure_pipelines/templates/terraform-outputs.yml
            parameters:
              azureServiceConnectionName: $(azure_service_principal_name)
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform/enablers
              terraformVersion: ${{ variables.terraformVersion }}
              terraformResourceGroupName: ${{ variables.terraformResourceGroupName }}
              terraformSaName: ${{ variables.terraformSaName }}
              terraformBackendContainerName: ${{ variables.terraformBackendContainerName }}

          - template: azure_pipelines/templates/terraform-outputs.yml
            parameters:
              azureServiceConnectionName: $(azure_service_principal_name)
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform/infrastructure
              terraformVersion: ${{ variables.terraformVersion }}
              terraformResourceGroupName: ${{ variables.terraformResourceGroupName }}
              terraformSaName: ${{ variables.terraformSaName }}
              terraformBackendContainerName: ${{ variables.terraformBackendContainerName }}

          - template: azure_pipelines/templates/azcli/pe-create-delete.yml
            parameters:
              azureServiceConnectionName: $(azure_service_principal_name)
              workingDirectory: $(System.DefaultWorkingDirectory)
              action: create
              location: $(terraform_in_location)
              privateEndpointBaseName: dbw-$(terraform_in_environment_type)-$(terraform_in_project)-$(terraform_in_location_short)
              resourceGroupName: $(terraform_out_resource_group_name)
              privateEndpointConnectionResourceId: $(terraform_out_databricks_id)
              privateEndpointSubnetId: $(terraform_out_endpoints_subnet_id)
              subresourceName: browser_authentication

          - template: azure_pipelines/templates/rotate-a-dns-records-steps.yml
            parameters:
              condition: and(not(failed()), not(canceled()))
              azureServiceConnectionName: $(azure_service_principal_name)
              dnsZoneSubscriptionID: $(private_dns_zone_subscription_id)
              dnsZoneResourceGroupName: $(private_dns_zone_resource_group)
              privateEndpointResourceGroupName: $(terraform_out_resource_group_name)
              privateDns:
                - substring: browser_authentication
                  name: privatelink.azuredatabricks.net
              aDnsRecords:
                - name: $(terraform_in_location).pl-auth
                  targetResourceSubstring: region
                  fromPrivateEndpoint: true
                  usePrivateEndpointName: true
                  privateEndpointName: pe-dbw-$(terraform_in_environment_type)-$(terraform_in_project)-$(terraform_in_location_short)-browser_authentication
                  ttl_seconds: 10
                  dnsSubstrings:
                    - subresource: browser_authentication
                      peFqdnSuffix: .azuredatabricks.net
                - name: $(terraform_in_location)-c2.pl-auth
                  targetResourceSubstring: regionc2
                  fromPrivateEndpoint: true
                  usePrivateEndpointName: true
                  privateEndpointName: pe-dbw-$(terraform_in_environment_type)-$(terraform_in_project)-$(terraform_in_location_short)-browser_authentication
                  ttl_seconds: 10
                  dnsSubstrings:
                    - subresource: browser_authentication
                      peFqdnSuffix: .azuredatabricks.net
                - name: $(terraform_in_location)-c3.pl-auth
                  targetResourceSubstring: regionc3
                  fromPrivateEndpoint: true
                  usePrivateEndpointName: true
                  privateEndpointName: pe-dbw-$(terraform_in_environment_type)-$(terraform_in_project)-$(terraform_in_location_short)-browser_authentication
                  ttl_seconds: 10
                  dnsSubstrings:
                    - subresource: browser_authentication
                      peFqdnSuffix: .azuredatabricks.net