parameters:
- name: resource
  displayName: Select the resource
  type: string
  default: keyvault
  values:
  - keyvault
  - storageaccount

- name: filerestore
  displayName: Add the file name backup to restore.
  type: string
  default: empty

- name: secretRestore
  displayName: All or single secret to restore.
  type: string
  default: all

- name: env
  displayName: Environment to run
  type: string
  default: demo
  values:
  - demo
  - uat
  - sit

trigger:
- none

pool:
  # default is the agent pool on private AKS
  name: default
  demands:
  - machine -equals aksprivate

extends:
  template: azure_pipelines/restore-pl.yml
  parameters:
    env: ${{ parameters.env }}
    resource: ${{ parameters.resource }}
    filerestore: ${{ parameters.filerestore }}
    secretRestore: ${{ parameters.secretRestore }}