{{- range $key, $value := .Values.vertica.subclusters }}
{{- if $value.verticaAutoscaler }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ $.Release.Namespace }}-{{ $value.service.name }}
spec:
  scaleTargetRef:
    apiVersion: vertica.com/v1beta1
    kind: VerticaAutoscaler
    name: {{ $.Release.Name }}-{{ $.Release.Namespace }}-{{ $value.service.name }}
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: ContainerResource
      containerResource:
        name: memory
        container: {{ $value.verticaAutoscaler.containerName }}
        target:
          type: Utilization
          averageUtilization: 90
    - type: ContainerResource
      containerResource:
        name: cpu
        container: {{ $value.verticaAutoscaler.containerName }}
        target:
          type: Utilization
          averageUtilization: 80
---
{{- end }}
{{- end }}