{{- range $key, $value := .Values.vertica.subclusters }}
{{- if $value.verticaAutoscaler }}
apiVersion: vertica.com/v1beta1
kind: VerticaAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ $.Release.Namespace }}-{{ $value.service.name }}
spec:
  serviceName: {{ $value.service.name }}
  verticaDBName: {{ $.Release.Name }}-{{ $.Release.Namespace }}
  {{- if $value.verticaAutoscaler.scalingGranularity }}
  scalingGranularity: {{ $value.verticaAutoscaler.scalingGranularity }}
  {{- end }}
  {{- if $value.verticaAutoscaler.targetSize }}
  targetSize: {{ $value.verticaAutoscaler.targetSize }}
  {{- end }}
  {{- if $value.verticaAutoscaler.template }}
  template: 
    - name: {{ $value.verticaAutoscaler.template.name }}
      {{- with $value.verticaAutoscaler.template.affinity }}
      affinity: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.externalIPs }}
      externalIPs: {{ $value.verticaAutoscaler.template.externalIPs }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.imageOverride }}
      imageOverride: {{ $value.verticaAutoscaler.template.imageOverride }}
      {{- end }}
      isPrimary: {{ $value.verticaAutoscaler.template.isPrimary }}
      isTransient: {{ $value.verticaAutoscaler.template.isTransient }}
      {{- if $value.verticaAutoscaler.template.loadBalancerIP }}
      loadBalancerIP: {{ $value.verticaAutoscaler.template.loadBalancerIP }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.nodePort }}
      nodePort: {{ $value.verticaAutoscaler.template.nodePort }}
      {{- end }}
      {{- with $value.verticaAutoscaler.template.nodeSelector }}
      nodeSelector: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.priorityClassName }}
      priorityClassName: {{ $value.verticaAutoscaler.template.priorityClassName }}
      {{- end }}
      {{- with $value.verticaAutoscaler.template.resources }}
      resources: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $value.verticaAutoscaler.template.serviceAnnotations }}
      serviceAnnotations: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.serviceName }}
      serviceName: {{ $value.verticaAutoscaler.template.serviceName }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.serviceType }}
      serviceType: {{ $value.verticaAutoscaler.template.serviceType }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.size }}
      size: {{ $value.verticaAutoscaler.template.size }}
      {{- end }}
      {{- with $value.verticaAutoscaler.template.tolerations }}
      tolerations: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if $value.verticaAutoscaler.template.verticaHTTPNodePort }}
      verticaHTTPNodePort: {{ $value.verticaAutoscaler.template.verticaHTTPNodePort }}
      {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}