parameters:
- name: project
  displayName: Project to use
  type: string
  default: enablers
  values:
  - enablers
  - infrastructure

- name: resource
  displayName: Resource to use
  type: string
  default: networks
  values:
  - resourcegroup
  - networks
  - aks
  - acr
  - appinsights
  - datalake
  - keyvault
  - postgresql
  - redis
  - storageaccount
  - airflow
  - aml
  - databricks
  - vertica
  - private_dns_zone

- name: env
  displayName: Environment to run
  type: string
  default: demo
  values:
  - demo
  - uat
  - sit

trigger:
- none

extends:
  template: azure_pipelines/testing-pl.yml
  parameters:
    vmImage: ubuntu-latest
    env: ${{ parameters.env }}
    resource: ${{ parameters.resource }}
    project: ${{ parameters.project }}