apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.airflow-pgbouncer-rules
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  types:
    - Ingress
    - Egress
  selector: app == 'airflow' && component == 'pgbouncer'
  ingress:
  - action: Allow
    destination:
      ports:
        - 6432
    protocol: TCP
    source:
      selector: app == 'airflow'
  egress:
  - action: Allow
    destination:
      ports:
        - {{ .Values.airflow.externalDatabase.port }}
      nets:
        - {{ .Values.calico.cidrs.postgresql }}
    protocol: TCP
