apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.airflow-general-rules
  namespace: {{ .Release.Namespace }}
spec:
  order: 11
  types:
  - Ingress
  - Egress
  selector: app == 'airflow'
  ingress:
    - action: Allow
      source:
        namespaceSelector: projectcalico.org/name == 'kube-system'
      protocol: TCP
  egress:
    - action: Allow
      destination:
        ports:
          - 80
        nets:
          - {{ .Values.calico.cidrs.metadata.endpoint }}
      protocol: TCP
    - action: Allow
      destination:
        ports:
          - 443
        nets:
          - {{ .Values.calico.cidrs.aks.internalApi }}
          - {{ .Values.calico.cidrs.aks.nodes }}
          - {{ .Values.calico.cidrs.endpoints }}
          {{- range $key, $val := .Values.calico.cidrs.databricks }}
          - {{ $val }}
          {{- end }}
          {{- range $key, $val := .Values.calico.cidrs.microsoft }}
          - {{ $val }}
          {{- end }}
      protocol: TCP
    - action: Allow
      destination:
        ports:
          - {{ .Values.airflow.externalDatabase.port }}
        nets:
          - {{ .Values.calico.cidrs.postgresql }}
      protocol: TCP
    - action: Allow
      destination:
        ports:
          - 587
      protocol: TCP
    - action: Allow
      destination:
        selector: app == 'airflow'
        namespaceSelector: projectcalico.org/name == {{ .Release.Namespace | squote }}
      protocol: TCP
    - action: Allow
      destination:
        namespaceSelector: projectcalico.org/name == 'kube-system'
      protocol: TCP
    - action: Allow
      destination:
        ports:
          - 53
        selector: k8s-app == 'kube-dns'
        namespaceSelector: projectcalico.org/name == 'kube-system'
      protocol: UDP
