apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.airflow-web-inbound
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  types:
  - Ingress
  selector: app == 'airflow' && component == 'web'
  ingress:
    - action: Allow
      destination:
        ports:
        - {{ .Values.airflow.web.service.externalPort }}
      protocol: TCP
      source:
        selector: app == 'airflow'
    - action: Allow
      destination:
        ports:
        - {{ .Values.airflow.web.service.externalPort }}
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == {{ .Values.ingressController.namespace | squote }}
        selector: controller == {{ .Values.ingressController.name | squote }}
