---
# Create a Secret to hold the name and key of the Storage Account
# Remember: values are base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: azureblob-secret
type: Opaque
data:
  azurestorageaccountname: "{{ .Values.airflow_sa_name  | b64enc }}"
  azurestorageaccountkey: "{{ .Values.airflow_sa_key  | b64enc }}"