trigger:
- none

schedules:
- cron: '0 17 * * 1-5'
  displayName: Daily midnight build
  always: true  
  branches:
    include:
    - main

parameters:
  - name: versionToSet
    displayName: ADO agent Version to set
    type: string
    default: 2.3.1-latest
  - name: azureContainerRegistry
    type: string
    default: 'acrdevdaweucentral'
  - name: azureGlobalContainerRegistry
    type: string
    default: 'acrdevdaweucentral'
  - name: azureGlobalContainerRegistryRg
    type: string
    default: 'rg-d-da-weu-central-manual'
  - name: environmentName
    displayName: where to build
    type: string
    default: d

variables:
  - group: ${{ parameters.environmentName }}
  - name: project_name
    value: igtpoc
  - name: common_feed_name
    value: common         
  - name: aksDevOpsNamespace
    value: ${{ parameters.environmentName }}-agentpool    
  - name: terraformVersion
    value: "1.5.0"
  - name: terraformResourceGroupName
    value: rg-$(terraform_in_environment_type)-$(terraform_in_project)-$(terraform_in_location_short)-state
  - name: terraformSaName
    value: sa$(terraform_in_environment_type)$(terraform_in_project)$(terraform_in_location_short)tfstate        
  - name: terraformBackendContainerName
    value: $(terraform_in_environment_type)tfstate    

stages:
- stage: Build_and_Push
  displayName: Build and Push image
  pool: 
    name: ${{ variables.aksDevOpsNamespace }} 
  jobs:
  - job: build_and_push
    displayName: Build and Push image
    steps:
      - checkout: self
        path: s/devops  

      - template: ../azure_pipelines/templates/docker-steps.yml
        parameters:
          versionToSet:  ${{ parameters.versionToSet }}
          dockerDirectory: $(System.DefaultWorkingDirectory)/docker/ado-agents
          azureServiceConnectionName: $(azure_service_principal_name)
          azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
          imageName: ado-agents
          azureGlobalContainerRegistry: ${{ parameters.azureGlobalContainerRegistry }}
          azureGlobalContainerRegistryRg: ${{ parameters.azureGlobalContainerRegistryRg }}
          aksDevOpsNamespace: ${{ variables.aksDevOpsNamespace }}         
          terraformVersion: ${{ variables.terraformVersion }} 
          terraformResourceGroupName: ${{ variables.terraformResourceGroupName }}
          terraformSaName: ${{ variables.terraformSaName }}
          terraformBackendContainerName: ${{ variables.terraformBackendContainerName }}                 
          dockerArgs: ''
          buildxTag: $(buildx_tag)          