apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ado-deployer
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - get
  - delete
