apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ado-deployer
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ado-deployer
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-agent
