apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ado-pods
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - list
  - create
