calico:
  cidrs:
    postgresql: null
    endpoints: null
    databricks:
      webapp_primary: 52.232.19.246/32
      webapp_weu_secondary: 40.74.30.80/32
      webapp_neu_secondary: 20.38.84.81/32
    microsoft:
      login_first: 20.20.32.0/19
      login_second: 20.190.128.0/18
      login_third: 20.231.128.0/19
      login_fourth: 40.126.0.0/18
    aks:
      internalApi: 10.0.0.1/32
      nodes: null
      services: 10.0.0.0/16
      pods: 10.244.0.0/16
    metadata:
      endpoint: 169.254.169.254/32

airflow:
  externalDatabase:
    port: 5432        
  web:
    service:
      externalPort: 8080  

ingressController:
  name: ingress-nginx
  namespace: ingress-controller      

# vertica:
#   namespace: vertica  