variables:
  - group: d
  - name: pool
    value: "d-agentpool"

trigger:
- none

schedules:
- cron: '0 18 * * 1-5'
  displayName: Daily midnight build
  always: true
  branches:
    include:
    - main

stages:
  - stage: acr_cleanup
    displayName: ACR cleanup
    jobs:
      - job: acr_cleanup
        displayName: ACR cleanup
        pool: 
          name: $(pool)
        steps:              
          - checkout: self        
          - template: ../azure_pipelines/templates/azcli/az-run-script.yml
            parameters:
              scriptPath: $(System.DefaultWorkingDirectory)/acr-script/download-and-install.ps1
              scriptType: pscore
              errorActionPreference: continue
              failOnStandardError: false
              azureServiceConnectionName: $(azure_service_principal_name)
              workingDirectory: $(System.DefaultWorkingDirectory)/acr-script/     

          - template: ../azure_pipelines/templates/azcli/az-run-script.yml
            parameters:
              scriptPath: $(System.DefaultWorkingDirectory)/acr-script/acr-cleanup.ps1
              scriptType: pscore
              errorActionPreference: continue
              failOnStandardError: false
              azureServiceConnectionName: $(azure_service_principal_name)
              workingDirectory: $(System.DefaultWorkingDirectory)/acr-script/     
              scriptArguments: acrddaweumain
              addSpnToEnvironment: true

          - template: ../azure_pipelines/templates/azcli/az-run-script.yml
            parameters:
              scriptPath: $(System.DefaultWorkingDirectory)/acr-script/acr-cleanup.ps1
              scriptType: pscore
              errorActionPreference: continue
              failOnStandardError: false
              azureServiceConnectionName: $(azure_service_principal_name)
              workingDirectory: $(System.DefaultWorkingDirectory)/acr-script/     
              scriptArguments: acrdevdaweucentral              
              addSpnToEnvironment: true