apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.{{ .Release.Name }}-allow-rules
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ index .Values "ingress-nginx" "controller" "containerPort" "https" }}
      source:
        nets:
          - {{ .Values.calico.cidrs.agents.nodes }}
        {{- range $key, $val := .Values.calico.cidrs.intrum }}
          - {{ toString $val }}
        {{- end }}
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ index .Values "ingress-nginx" "controller" "containerPort" "https" }}
          - {{ index .Values "ingress-nginx" "controller" "admissionWebhooks" "port" }}
          - {{ index .Values "ingress-nginx" "controller" "metrics" "port" }}
      source:
        nets:
          - {{ .Values.calico.cidrs.aks.nodes }}
          - {{ .Values.calico.cidrs.aks.pods }}
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ index .Values "ingress-nginx" "controller" "containerPort" "https" }}
      source:
        nets:
          - {{ .Values.calico.cidrs.aks.azureComm }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        nets:
        - {{ .Values.calico.cidrs.aks.nodes }}
        - {{ .Values.calico.cidrs.aks.pods }}
    - action: Allow
      destination:
        ports:
          - 53
        selector: k8s-app == 'kube-dns'
        namespaceSelector: projectcalico.org/name == 'kube-system'
      protocol: UDP
    - action: Allow
      protocol: TCP
      destination:
        nets:
        - {{ .Values.calico.cidrs.aks.internalApi }}
        ports:
        - 443