parameters:
  - name: azureServiceConnectionName
    type: string
  - name: terraformVersion
    type: string
  - name: terraformResourceGroupName
    displayName: Resource group for Terraform state of environment
    type: string
  - name: terraformSaName
    displayName: Storage Account name for Terraform state of environment
    type: string
  - name: terraformBackendContainerName
    displayName: SA Container name for Terraform state of environment
    type: string
  - name: resourceGroupName
    displayName: Databricks resource group name
    type: string
  - name: keyVaultName
    displayName: Key vault name
    type: string
  - name: keyVaultSecretNames
    displayName: Key vault secret names
    type: object
  - name: azClientIdName
    displayName: Key vault secret name to get the Client Id used for AZ CLI
    type: string
  - name: azClientSecretName
    displayName: Key vault secret name to get the Client Secret used for AZ CLI
    type: string
  - name: databricksSpnPatTokenName
    displayName: Databricks service principal keyvault secret name
    type: string
  - name: databricksSpnPatTokenId
    displayName: Databricks service principal keyvault secret id
    type: string
  - name: infrastructureModule
    displayName: Infrastructure module name
    type: string
  - name: pool
    displayName: Agent pool name to run jobs
    type: string
  - name: comment
    displayName: Comment
    type: string
  - name: condition
    displayName: Condition to run the stage
    type: string
    default: ""
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: service_principal_databricks_token_creation
    displayName: Service principal databricks token creation
    dependsOn: ${{ parameters.dependsOn }}
    ${{ if ne(parameters.condition, '') }}:
      condition: ${{ parameters.condition }}
    jobs:
      - job: service_principal_token_creation
        displayName: Service principal token creation
        pool: 
          ${{ if ne(parameters['pool'], 'ubuntu-latest') }}:
            name: ${{ parameters.pool }}
          ${{ if eq(parameters['pool'], 'ubuntu-latest') }}:
            vmImage: ${{ parameters.pool }}
        steps:
          - template: templates/create-databricks-token-steps.yml
            parameters:
              azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
              terraformVersion: ${{ parameters.terraformVersion }}
              terraformResourceGroupName: ${{ parameters.terraformResourceGroupName }}
              terraformSaName: ${{ parameters.terraformSaName }}
              terraformBackendContainerName: ${{ parameters.terraformBackendContainerName }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              keyVaultName: ${{ parameters.keyVaultName }}
              keyVaultSecretNames: ${{ parameters.keyVaultSecretNames }}
              databricksSpnPatTokenName: ${{ parameters.databricksSpnPatTokenName }}
              databricksSpnPatTokenId: ${{ parameters.databricksSpnPatTokenId }}
              infrastructureModule: ${{ parameters.infrastructureModule }}
              azClientIdName: ${{ parameters.azClientIdName }}
              azClientSecretName: ${{ parameters.azClientSecretName }}
              comment: ${{ parameters.comment }}

