
trigger:
- none

parameters:
  - name: azureServiceConnectionName
    type: string
    default: 'sc_datamngtdev_poc'
  - name: storageAccount
    type: string
    default: 'sadadevopsbackups'
  - name: vmImage
    default: 'default'
  - name: envSource
    type: string
    default: demo
  - name: envTarget
    type: string
    default: demo
  - name: sourceFileParam
    type: string
    default: " "
  - name: selectedModelListParam
    type: string
    default: " "
  - name: restoreAsNewVersionParam
    type: boolean
    default: false


variables:
#  - group: ServicePrincipal
  - name: storageAccountName
    value: "${{parameters.storageAccount}}"
  - name: resourceGroupName
    value: "rg-aml-da-${{parameters.envTarget}}"
  - name: workspaceName
    value: "amlwda${{parameters.envTarget}}"
  - name: sourceFile
    ${{ if eq( parameters['sourceFileParam'], ' ') }}:
      value: "Newest"
    ${{ else }}:
      value: "${{parameters.sourceFileParam}}"
  - name: selectedModelList
    ${{ if eq( parameters['selectedModelListParam'], ' ') }}:
      value: "All"
    ${{ else }}:
      value: "${{parameters.selectedModelListParam}}"
  - name: restoreAsNewVersion
    ${{ if eq( parameters['restoreAsNewVersionParam'], true) }}:
      value: "-restoreAsNewVersion"

stages:
- stage: Restore
  pool:
    # default is the AgentPool for Private AKS
    vmImage: ${{ parameters.vmImage }}

  jobs:
  - job: Restore_Models
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: '${{ parameters.azureServiceConnectionName }}'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: 'azure_pipelines/scripts/restore-model.ps1'
        arguments: '-env ${{parameters.envSource}} -resourceGroupName  $(resourceGroupName) -workspaceName $(workspaceName) -storageAccountName  $(storageAccountName) -sourceFile $(sourceFile) -selectedModelList $(selectedModelList) $(restoreAsNewVersion)'
        powerShellErrorActionPreference: 'continue'
      displayName: 'Executing Restore Models'
      condition: True



