parameters:
- name: azureServiceConnectionName
  displayName: Azure Service Connection name
  type: string
- name: pool
  displayName: Agent pool to run the jobs.
  type: string
- name: mainKeyVaultName
  displayName: Main Key Vault Name
  type: string
- name: masterKeyVaultName
  displayName: Master Key Vault Name
  type: string
- name: keyVaultSecretNames
  displayName: Key Vault Secret Names
  type: object
  default: []


stages:
- stage: rotate_credentials
  displayName: Rotate credentials stage
  jobs:
  - job: rotate_credentials_job
    displayName: Rotate credentials job
    pool:
      ${{ if ne(parameters.pool, 'ubuntu-latest') }}:
        name: ${{ parameters.pool }}
      ${{ if eq(parameters.pool, 'ubuntu-latest') }}:
        vmImage: ${{ parameters.pool }}
    steps:
    - template: templates/rotate-credentials-steps.yml
      parameters:
        azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
        mainKeyVaultName: ${{ parameters.mainKeyVaultName }}
        masterKeyVaultName: ${{ parameters.masterKeyVaultName }}
        keyVaultSecretNames: ${{ parameters.keyVaultSecretNames }}