parameters:
- name: azureServiceConnectionName
  displayName: Azure Service Connection name
  type: string
- name: pool
  displayName: Agent pool to run the jobs.
  type: string
- name: resourceGroupName
  displayName: Resource Group Name where the storage accounts are.
  type: string
- name: keyVaultName
  displayName: Key Vault Name to store the keys.
  type: string
- name: storageAccounts
  displayName: Storage account objects.
  type: object
  default: []


stages:
- stage: rotate_keys_stage
  displayName: Rotate keys stage
  jobs:
  - ${{ each storageAccount in parameters.storageAccounts }}:
    - job: rotate${{ storageAccount.keyVaultSecretName }}
      displayName: Rotate ${{ storageAccount.keyVaultSecretName }}
      pool:
        ${{ if ne(parameters.pool, 'ubuntu-latest') }}:
          name: ${{ parameters.pool }}
        ${{ if eq(parameters.pool, 'ubuntu-latest') }}:
          vmImage: ${{ parameters.pool }}
      steps:
      - checkout: none
      - template: templates/rotate-sa-keys-steps.yml
        parameters:
          azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          saName: ${{ storageAccount.saName }}
          keyVaultName: ${{ parameters.keyVaultName }}
          keyVaultSecretName: ${{ storageAccount.keyVaultSecretName }}