parameters:
  - name: azureServiceConnectionName
    type: string
  - name: terraformVersion
    type: string
  - name: terraformResourceGroupName
    displayName: Resource group for Terraform state of environment
    type: string
  - name: terraformSaName
    displayName: Storage Account name for Terraform state of environment
    type: string
  - name: terraformBackendContainerName
    displayName: SA Container name for Terraform state of environment
    type: string
  - name: mainResourceGroupName
    displayName: Main resource group
    type: string
  - name: kvTestSuiteResourceGroupName
    displayName: Test Suite Key Vault resource group
    type: string
  - name: enablersModule
    displayName: Enablers module name
    type: string
    default: enablers
  - name: infrastructureModule
    displayName: Infrastructure module name
    type: string
    default: infrastructure
  - name: contentModule
    displayName: content module name
    type: string
    default: content
  - name: mainKeyVaultName
    displayName: Key vault name
    type: string    
  - name: mainKeyVaultSecretNames
    displayName: Key vault secret names
    type: object
  - name: testKeyVaultName
    displayName: Key vault name
    type: string    
  - name: testKeyVaultSecretNames
    displayName: Key vault secret names
    type: object
  - name: testRepositoryCheckout
    displayName: Test suits repository to checkout
    type: string
  - name: devopsRepositoryCheckout
    displayName: Devops repository to checkout
    type: string
  - name: pool
    type: string
  - name: saPublicAccessUpdate
    displayName: Storage Account Public Access Update
    type: boolean
  - name: mavenPomFile
    displayName: Maven test suite pom file path
    type: string
  - name: mavenGoal
    displayName: Maven test goal
    type: string
  - name: mavenOptions
    displayName: Maven options
    type: string
  - name: condition
    displayName: Condition to run the stage
    type: string
    default: ""
  - name: firstBlockProfiles
    displayName: First block of parallel profiles
    type: object
    default: []
  - name: secondBlockProfiles
    displayName: Second block of parallel profiles
    type: object
    default: []
  - name: dependsOn
    type: object
    default: [ ]

stages:
  - ${{ each firstBlockProfile in parameters.firstBlockProfiles }}:
    - stage: ${{firstBlockProfile}}
      displayName: '${{ firstBlockProfile }} tests'
      dependsOn: ${{ parameters.dependsOn }}
      ${{ if ne(parameters.condition, '') }}:
        condition: ${{ parameters.condition }}
      jobs:
        - job: run_test_suite
          displayName: '${{ firstBlockProfile }} tests'
          timeoutInMinutes: 120
          workspace:
            clean: all
          pool:
            name: ${{ parameters.pool }}
          steps:
            - checkout: ${{ parameters.testRepositoryCheckout }}
              path: s/test-suite
              lfs: true
            - checkout: ${{ parameters.devopsRepositoryCheckout }}
              path: s/devops

            - template: templates/test-suite-steps.yml
              parameters:
                azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
                terraformVersion: ${{ parameters.terraformVersion }}
                terraformResourceGroupName: ${{ parameters.terraformResourceGroupName }}
                terraformSaName: ${{ parameters.terraformSaName }}
                terraformBackendContainerName: ${{ parameters.terraformBackendContainerName }}
                mainResourceGroupName: ${{ parameters.mainResourceGroupName }}
                kvTestSuiteResourceGroupName: ${{ parameters.kvTestSuiteResourceGroupName }}
                mainKeyVaultName: ${{ parameters.mainKeyVaultName }}
                mainKeyVaultSecretNames: ${{ parameters.mainKeyVaultSecretNames }}
                testKeyVaultName: ${{ parameters.testKeyVaultName }}
                testKeyVaultSecretNames: ${{ parameters.testKeyVaultSecretNames }}
                saPublicAccessUpdate: ${{ parameters.saPublicAccessUpdate }}
                mavenOptions: >-
                  ''\''${{ parameters.mavenOptions }}'\'''
                mavenProfiles: ${{ firstBlockProfile }}
                mavenPomFile: ${{ parameters.mavenPomFile }}
                mavenGoal: ${{ parameters.mavenGoal }}
                continueOnError: true
  - ${{ each secondBlockProfile in parameters.secondBlockProfiles }}:
    - stage: ${{secondBlockProfile}}
      displayName: '${{secondBlockProfile}} tests'
      dependsOn:
        - ${{each profile in parameters.firstBlockProfiles}}:
          - ${{profile}}
      jobs:
        - job: ${{secondBlockProfile}}_tests
          displayName: '${{secondBlockProfile}} tests'
          timeoutInMinutes: 120
          workspace:
            clean: all
          pool:
            name: ${{ parameters.pool }}
          steps:
            - checkout: ${{ parameters.testRepositoryCheckout }}
              path: s/test-suite
              lfs: true
            - checkout: ${{ parameters.devopsRepositoryCheckout }}
              path: s/devops

            - template: templates/test-suite-steps.yml
              parameters:
                azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
                terraformVersion: ${{ parameters.terraformVersion }}
                terraformResourceGroupName: ${{ parameters.terraformResourceGroupName }}
                terraformSaName: ${{ parameters.terraformSaName }}
                terraformBackendContainerName: ${{ parameters.terraformBackendContainerName }}
                mainResourceGroupName: ${{ parameters.mainResourceGroupName }}
                kvTestSuiteResourceGroupName: ${{ parameters.kvTestSuiteResourceGroupName }}
                mainKeyVaultName: ${{ parameters.mainKeyVaultName }}
                mainKeyVaultSecretNames: ${{ parameters.mainKeyVaultSecretNames }}
                testKeyVaultName: ${{ parameters.testKeyVaultName }}
                testKeyVaultSecretNames: ${{ parameters.testKeyVaultSecretNames }}
                saPublicAccessUpdate: ${{ parameters.saPublicAccessUpdate }}
                mavenOptions: >-
                  ''\''${{ parameters.mavenOptions }}'\'''
                mavenProfiles: ${{ secondBlockProfile }}
                mavenPomFile: ${{ parameters.mavenPomFile }}
                mavenGoal: ${{ parameters.mavenGoal }}
                continueOnError: true