parameters:
  - name: azureServiceConnectionName
    type: string
  - name: terraformVersion
    type: string
  - name: kubectlVersion
    type: string
  - name: helmVersion
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: resourceGroupName
    displayName: Environment resource group name
    type: string
  - name: dnsZoneSubscriptionID
    displayName: Private DNS zone's for A records subscription ID
    type: string
  - name: dnsZoneResourceGroupName
    displayName: Private DNS Zone resource group name
    type: string
  - name: terraformResourceGroupName
    displayName: Resource group for Terraform state of environment
    type: string
  - name: terraformSaName
    displayName: Storage Account name for Terraform state of environment
    type: string
  - name: terraformBackendContainerName
    displayName: SA Container name for Terraform state of environment
    type: string
  - name: operatorReleaseName
    displayName: Vertica Operator Helm release name
    type: string
    default: vertica-operator
  - name: helmReleaseName
    displayName: Vertica DB Helm release name
    type: string
  - name: helmNamespace
    displayName: Vertica DB Helm release namespace
    type: string
  - name: airflowNamespace
    displayName: Airflow namespace
    type: string
  - name: pool
    displayName: Agent pool name to run jobs
    type: string
  - name: keyVaultName
    displayName: Key vault name
    type: string
  - name: keyVaultSecretNames
    displayName: Key vault secret names
    type: object
    default: 
      - verticatlskey
      - verticatlscrt
      - verticatlscakey
      - verticatlscacrt
      - verticatlswebhookkey
      - verticatlswebhookcrt
      - verticasupassword
      - saverticakey
  - name: saPublicAccessUpdate
    displayName: Storage Account Public Access Update
    type: boolean
  - name: condition
    displayName: Condition to run the stage
    type: string
    default: ""
  - name: enablersModule
    displayName: Enablers module name
    type: string
  - name: infrastructureModule
    displayName: Infrastructure module name
    type: string
  - name: verticaTag
    displayName: version to deploy
  - name: verticaLoggerTag
    displayName: version to deploy for vertica logger
  - name: verticaOperatorTag
    displayName: version to deploy      

stages:
  - stage: vertica_deployment
    displayName: Vertica deployment
    dependsOn: ${{ parameters.dependsOn }}
    ${{ if ne(parameters.condition, '') }}:
      condition: ${{ parameters.condition }}
    jobs:
      - job: vertica_deployment_install
        displayName: Install Vertica chart
        pool: 
          ${{ if ne(parameters['pool'], 'ubuntu-latest') }}:
            name: ${{ parameters.pool }}
          ${{ if eq(parameters['pool'], 'ubuntu-latest') }}:
            vmImage: ${{ parameters.pool }}
        steps:
          - template: templates/vertica-steps.yml
            parameters:
              azureServiceConnectionName: ${{ parameters.azureServiceConnectionName }}
              terraformVersion: ${{ parameters.terraformVersion }}
              kubectlVersion: ${{ parameters.kubectlVersion }}
              helmVersion: ${{ parameters.helmVersion }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              dnsZoneSubscriptionID: ${{ parameters.dnsZoneSubscriptionID }}
              dnsZoneResourceGroupName: ${{ parameters.dnsZoneResourceGroupName }}
              terraformResourceGroupName: ${{ parameters.terraformResourceGroupName }}
              terraformSaName: ${{ parameters.terraformSaName }}
              terraformBackendContainerName: ${{ parameters.terraformBackendContainerName }}
              keyVaultName: ${{ parameters.keyVaultName }}
              keyVaultSecretNames: ${{ parameters.keyVaultSecretNames }}
              saPublicAccessUpdate: ${{ parameters.saPublicAccessUpdate }}
              enablersModule: ${{ parameters.enablersModule }}
              infrastructureModule: ${{ parameters.infrastructureModule }}
              operatorReleaseName: ${{ parameters.operatorReleaseName }}
              helmReleaseName: ${{ parameters.helmReleaseName }}
              helmNamespace: ${{ parameters.helmNamespace }}
              airflowNamespace: ${{ parameters.airflowNamespace }}
              verticaTag: ${{ parameters.verticaTag }}
              verticaLoggerTag: ${{ parameters.verticaLoggerTag }}
              verticaOperatorTag: ${{ parameters.verticaOperatorTag }}
