kind: ConfigMap
apiVersion: v1
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
  # more info: https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-logging-v2
  #            https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-agent-config
  # original file: https://raw.githubusercontent.com/microsoft/Docker-Provider/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml
data:
  schema-version:
    v1

  config-version:
    ver1

  log-data-collection-settings: |-
    [log_collection_settings]
      [log_collection_settings.stdout]
        enabled = true
        exclude_namespaces = ["default","kube-node-lease","kube-public","kube-system","calico-system","tigera-operator","ingress-controller","prometheus"]
      [log_collection_settings.stderr]
        enabled = true
        exclude_namespaces = ["default","kube-node-lease","kube-public","kube-system","calico-system","tigera-operator","ingress-controller","prometheus"]
      [log_collection_settings.env_var]
        enabled = false
      [log_collection_settings.enrich_container_logs]
        enabled = true
      [log_collection_settings.collect_all_kube_events]
        enabled = false
      [log_collection_settings.schema]
        #Customers can enable the ContainerLogV2 schema at the cluster level through either the cluster's Data Collection Rule (DCR) or ConfigMap.
        containerlog_schema_version = "v2"
      [log_collection_settings.enable_multiline_logs]
        enabled = "true"

  prometheus-data-collection-settings: |-
    [prometheus_data_collection_settings.cluster]
      interval = "1m"
      monitor_kubernetes_pods = false
    [prometheus_data_collection_settings.node]
      interval = "1m"

  metric_collection_settings: |-
    [metric_collection_settings.collect_kube_system_pv_metrics]
      enabled = false

  alertable-metrics-configuration-settings: |-
    [alertable_metrics_configuration_settings.container_resource_utilization_thresholds]
      container_cpu_threshold_percentage = 95.0
      container_memory_rss_threshold_percentage = 95.0
      container_memory_working_set_threshold_percentage = 95.0
    [alertable_metrics_configuration_settings.pv_utilization_thresholds]
      pv_usage_threshold_percentage = 60.0
    [alertable_metrics_configuration_settings.job_completion_threshold]
      job_completion_threshold_time_minutes = 360

  integrations: |-
    [integrations.azure_network_policy_manager]
      collect_basic_metrics = false
      collect_advanced_metrics = false
    [integrations.azure_subnet_ip_usage]
      enabled = false

# Doc - https://github.com/microsoft/Docker-Provider/blob/ci_prod/Documentation/AgentSettings/ReadMe.md
  agent-settings: |-
    [agent_settings.prometheus_fbit_settings]
      tcp_listener_chunk_size = 10
      tcp_listener_buffer_size = 10
      tcp_listener_mem_buf_limit = 200
