apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.{{ .Release.Name }}-rules
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  types:
    - Ingress
    - Egress
  selector: control-plane == 'controller-manager'
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - 8443
      source:
        selector: app.kubernetes.io/instance == 'prometheus'
        namespaceSelector: projectcalico.org/name == {{ .Values.prometheus.namespace | squote }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        serviceAccounts:
          names: 
            - {{ index .Values "verticadb-operator" "nameOverride" }}-controller-manager
        namespaceSelector: projectcalico.org/name == {{ .Release.Namespace | squote }}
    - action: Allow
      protocol: UDP
      destination:
        serviceAccounts:
          names: 
            - {{ index .Values "verticadb-operator" "nameOverride" }}-controller-manager
        namespaceSelector: projectcalico.org/name == {{ .Release.Namespace | squote }}
