apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.{{ .Release.Name }}-general-rules
  namespace: {{ .Release.Namespace }}
spec:
  order: 20
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      source:
        namespaceSelector: projectcalico.org/name == 'kube-system'
      protocol: TCP
  egress:
    - action: Allow
      destination:
        namespaceSelector: projectcalico.org/name == 'kube-system'
      protocol: TCP
    - action: Allow
      destination:
        ports:
          - 53
        selector: k8s-app == 'kube-dns'
        namespaceSelector: projectcalico.org/name == 'kube-system'
      protocol: UDP
    - action: Allow
      protocol: TCP
      destination:
        nets:
        - {{ .Values.calico.cidrs.aks.internalApi }}
        - {{ .Values.calico.cidrs.aks.externalApi }}
        - {{ .Values.calico.cidrs.endpoints }}
        ports:
        - 443
    - action: Allow
      protocol: TCP
      destination:
        nets:
        - {{ .Values.calico.cidrs.aks.azureMetadata }}
        ports:
        - 80