apiVersion: v1
data:
  tls.key: {{ required "operator.tls.key value must be provided" .Values.operator.tls.key }}
  tls.crt: {{ required "operator.tls.crt value must be provided" .Values.operator.tls.crt }}
  ca.crt: {{ required "operator.tls.ca.crt value must be provided" .Values.operator.tls.ca.crt }}
kind: Secret
metadata:
  name: vertica-operator-tls-secret
type: Opaque